desired_vel = 32;
initial_vel = 27;
flap_angle = 40;
motor_angle = 10;
initial_incidence = 1;
desired_gamma = 0;
initial_attitude = desired_gamma + initial_incidence;
initial_position = [0 -100];
initial_mass = 20;